// NOVA EDIT - I18N CODEMOD - 玩家可见字符串已改写为 LANG()；请勿手改 key，见 modular_nova/modules/i18n/readme.md
// the underfloor wiring terminal for the APC
// autogenerated when an APC is placed
// all conduit connects go to this object instead of the APC
// using this solves the problem of having the APC in a wall yet also inside an area

/obj/machinery/power/terminal
	name = "terminal"
	icon = 'icons/obj/pipes_n_cables/structures.dmi'
	icon_state = "term"
	desc = "It's an underfloor wiring terminal, used to draw power from the grid."
	layer = WIRE_TERMINAL_LAYER //a bit above wires
	var/obj/machinery/power/master = null


/obj/machinery/power/terminal/Initialize(mapload)
	. = ..()

	AddElement(/datum/element/undertile, TRAIT_T_RAY_VISIBLE, use_alpha = TRUE)

/obj/machinery/power/terminal/Destroy()
	if(master)
		master.disconnect_terminal()
		master = null
	return ..()

/obj/machinery/power/terminal/examine(mob/user)
	. = ..()
	if(!QDELETED(powernet))
		. += span_notice(LANG("obj.cb2b8542d36e115c", list(LOWER_TEXT(GLOB.cable_layer_to_name["[cable_layer]"]))))
	else
		. += span_warning(LANG("obj.90491e4d4428331b", list(LOWER_TEXT(GLOB.cable_layer_to_name["[cable_layer]"]))))

/obj/machinery/power/terminal/should_have_node()
	return TRUE

/obj/machinery/power/proc/can_terminal_dismantle()
	. = FALSE

/obj/machinery/power/apc/can_terminal_dismantle()
	. = FALSE
	if(opened)
		. = TRUE

/obj/machinery/power/smes/can_terminal_dismantle()
	. = FALSE
	if(panel_open)
		. = TRUE

/obj/machinery/power/terminal/proc/dismantle(mob/living/user, obj/item/I)
	if(isturf(loc))
		var/turf/T = loc
		if(T.underfloor_accessibility < UNDERFLOOR_INTERACTABLE)
			balloon_alert(user, LANG("obj.f56c1e1b8ad8cbb5", null))
			return

	if(master && !master.can_terminal_dismantle())
		return

	user.visible_message(span_notice(LANG("obj.3de03659b545c9ba", list(user.name, master))))
	balloon_alert(user, LANG("obj.3b4a022dac3a242a", null))

	playsound(src.loc, 'sound/items/deconstruct.ogg', 50, TRUE)
	if(I.use_tool(src, user, 50))
		if(master && !master.can_terminal_dismantle())
			return

		if(prob(50) && electrocute_mob(user, powernet, src, 1, TRUE))
			do_sparks(5, TRUE, master)
			return

		var/obj/item/stack/cable_coil/cable = new (drop_location(), 10)
		qdel(src)
		cable.balloon_alert(user, LANG("obj.9bb4a12a41b4bf31", null))

/obj/machinery/power/terminal/wirecutter_act(mob/living/user, obj/item/I)
	..()
	dismantle(user, I)
	return TRUE
