/obj/item/mecha_parts/mecha_equipment/weapon
	name = "机甲武器"
	abstract_type = /obj/item/mecha_parts/mecha_equipment/weapon
	range = MECHA_RANGED
	equipment_slot = MECHA_WEAPON
	destroy_sound = 'sound/vehicles/mecha/weapdestr.ogg'
	mech_flags = EXOSUIT_MODULE_COMBAT
	/// The type of bullet generated by the mecha weapon.
	var/projectile
	/// The sound of the mecha weapon firing.
	var/fire_sound
	/// How many shots are fired per action.
	var/projectiles_per_shot = 1
	/// The degrees by which each individual bullet fans out from a central point. A predictable spray of bullets.
	var/variance = 0
	/// Whether our bullets go off trajectory while firing randomly. Used to replicate recoil and not a structured, predictable spray.
	var/randomspread = FALSE
	/// The amount in deciseconds that the weapon sleeps between shots to simulate a 'burst fire'. The delay stops another bullet from being fired while sleeping.
	var/projectile_delay = 0
	//the visual effect appearing when the weapon is fired.
	var/firing_effect_type = /obj/effect/temp_visual/dir_setting/firing_effect
	/// Will using this weapon in no grav push mecha back.
	var/kickback = TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/special_attaching_interaction(attach_right = FALSE, obj/vehicle/sealed/mecha/mech, mob/user, checkonly = FALSE)
	var/obj/item/mecha_parts/mecha_equipment/concealed_weapon_bay/bay
	if(attach_right)
		bay = mech.equip_by_category[MECHA_R_ARM]
	else
		bay = mech.equip_by_category[MECHA_L_ARM]
	if(!istype(bay))
		return FALSE //No bay, use normal attach procs
	if(checkonly)
		return TRUE
	name = bay.name
	icon = bay.icon
	icon_state = bay.icon_state
	bay.detach()
	bay.forceMove(src) //for later detaching
	attach(mech, attach_right)
	user.visible_message(span_notice("[user]将某物插入[src]。"), span_notice("你将[initial(name)]安装进隐蔽武器舱。"))
	return TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/detach(atom/moveto)
	for(var/obj/item/mecha_parts/mecha_equipment/concealed_weapon_bay/bay in contents)
		bay.forceMove(get_turf(chassis))
	name = initial(name)
	icon = initial(icon)
	icon_state = initial(icon_state)
	return ..()

/obj/item/mecha_parts/mecha_equipment/weapon/action(mob/source, atom/target, list/modifiers)
	if(!action_checks(target))
		return FALSE

	/// Find our mecha, find the opposite direction. Used for kickback while the mecha is drifting in zero-g to launch us in this direction.
	var/newtonian_target = dir2angle(REVERSE_DIR(chassis.dir))
	. = ..()//start the cooldown early because of sleeps
	for(var/projectiles_to_shoot in 1 to projectiles_per_shot)
		if(energy_drain && !chassis.has_charge(energy_drain))//in case we run out of energy mid-burst, such as emp
			break
		var/spread = 0
		if(variance)
			if(randomspread)
				spread = round((rand(0 , 1) - 0.5) * variance, 1)
			else
				spread = round((projectiles_to_shoot / projectiles_per_shot - 0.5) * variance, 1)

		var/obj/projectile/projectile_obj = new projectile(get_turf(src))
		projectile_obj.log_override = TRUE //we log being fired ourselves a little further down.
		projectile_obj.firer = chassis
		projectile_obj.fired_from = src // mech = firer, equipment = fired from
		projectile_obj.aim_projectile(target, source, modifiers, spread)
		if(isliving(source) && source.client) //dont want it to happen from syndie mecha npc mobs, they do direct fire anyways
			var/mob/living/shooter = source
			projectile_obj.hit_prone_targets = shooter.combat_mode
		projectile_obj.fire()
		if(!projectile_obj.suppressed && firing_effect_type)
			new firing_effect_type(chassis || get_turf(src), chassis.dir)
		playsound(chassis, fire_sound, 50, TRUE)

		log_combat(source, target, "fired [projectile_obj] at", src, "from [chassis] at [get_area_name(src, TRUE)]")

		sleep(max(0, projectile_delay))

		if(kickback)
			chassis.newtonian_move(newtonian_target)
	chassis.log_message("[key_name(source)] fired [src], targeting [target].", LOG_ATTACK)

//Base energy weapon type
/obj/item/mecha_parts/mecha_equipment/weapon/energy
	name = "通用能量武器"
	firing_effect_type = /obj/effect/temp_visual/dir_setting/firing_effect/red

/obj/item/mecha_parts/mecha_equipment/weapon/energy/laser
	equip_cooldown = 8
	name = "\improper CH-PS \"献祭者\"镭射"
	desc = "一种用于作战的机甲装备，能够发射轻激光。"
	icon_state = "mecha_laser"
	energy_drain = 3 KILO JOULES
	projectile = /obj/projectile/beam/laser
	fire_sound = 'sound/items/weapons/laser.ogg'
	harmful = TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/energy/disabler
	equip_cooldown = 1.5 SECONDS
	name = "\improper CH-DS\"和平捍卫者\"骑兵镇暴光枪"
	desc = "一种用于战斗动力装甲的武器。发射多束弱效镇暴光束。"
	icon_state = "mecha_disabler"
	energy_drain = 10 KILO JOULES
	projectile = /obj/projectile/beam/disabler/weak
	variance = 25
	projectiles_per_shot = 5
	fire_sound = 'sound/items/weapons/taser2.ogg'
	firing_effect_type = /obj/effect/temp_visual/dir_setting/firing_effect/blue

/obj/item/mecha_parts/mecha_equipment/weapon/energy/laser/heavy
	equip_cooldown = 15
	name = "\improper CH-LC\"索利斯\"激光加农"
	desc = "一种用于作战的机甲装备，能够发射重激光。"
	icon_state = "mecha_laser"
	energy_drain = 6 KILO JOULES
	projectile = /obj/projectile/beam/laser/heavylaser
	fire_sound = 'sound/items/weapons/lasercannonfire.ogg'

/obj/item/mecha_parts/mecha_equipment/weapon/energy/ion
	equip_cooldown = 20
	name = "\improper MKIV 重型离子加农"
	desc = "一种用于作战的机甲装备，能够发射破坏敌方电子设备的离子束，切勿让自己处于影响范围！"
	icon_state = "mecha_ion"
	energy_drain = 1.2 KILO JOULES
	projectile = /obj/projectile/ion
	fire_sound = 'sound/items/weapons/laser.ogg'

/obj/item/mecha_parts/mecha_equipment/weapon/energy/tesla
	equip_cooldown = 35
	name = "\improper MKI特斯拉加农"
	desc = "一种用于作战的机甲装备，它能发射类似特斯拉引擎一样的电流。"
	icon_state = "mecha_ion"
	energy_drain = 5 KILO JOULES
	projectile = /obj/projectile/energy/tesla/cannon
	fire_sound = 'sound/effects/magic/lightningbolt.ogg'
	harmful = TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/energy/pulse
	equip_cooldown = 30
	name = "eZ-13 MK2 重型脉冲步枪"
	desc = "一件用于机甲的战斗装备，能够发射威力巨大的脉冲,足以摧毁任何敢于阻挡之物。"
	icon_state = "mecha_pulse"
	energy_drain = 1.2 KILO JOULES
	projectile = /obj/projectile/beam/pulse/heavy
	fire_sound = 'sound/items/weapons/marauder.ogg'
	harmful = TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/energy/plasma
	equip_cooldown = 10
	name = "217-D 重型等离子切割机"
	desc = "一种能以极高速度发射共振等离子体脉冲的装置。这些脉冲能够粉碎岩石以及坚固的障碍物。"
	icon_state = "mecha_plasmacutter"
	inhand_icon_state = "plasmacutter"
	lefthand_file = 'icons/mob/inhands/weapons/guns_lefthand.dmi'
	righthand_file = 'icons/mob/inhands/weapons/guns_righthand.dmi'
	energy_drain = 0.3 KILO JOULES
	projectile = /obj/projectile/plasma/adv/mech
	fire_sound = 'sound/items/weapons/plasma_cutter.ogg'
	harmful = TRUE
	mech_flags = EXOSUIT_MODULE_COMBAT | EXOSUIT_MODULE_WORKING

///Exosuit thermal guns

/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal
	equip_cooldown = 20
	name = "\improper 原型-I型'热能炮'"
	desc = "一种专为动力装甲设计的重型热能武器特殊原型。此型号为调试用版本。"
	icon_state = "mecha_laser"
	energy_drain = 5 KILO JOULES
	projectile = /obj/item/ammo_casing/energy/nanite
	fire_sound = 'sound/items/weapons/thermalpistol.ogg'
	harmful = TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/cryo
	name = "\improper 原型 I 型 '低温热能炮'"
	desc = "一款专为外骨骼设计的重型热能武器特殊原型。此型号为低温弹膛式。"
	icon_state = "mecha_cryogun"
	projectile = /obj/projectile/energy/cryo

/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/inferno
	name = "\improper 原型 II 型 '高温热能炮'"
	desc = "一款专为外骨骼设计的重型热能武器特殊原型。此型号为熔融弹膛式。"
	icon_state = "mecha_pyrogun"
	projectile = /obj/projectile/energy/inferno

/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/cryo/try_attach_part(mob/user, obj/vehicle/sealed/mecha/themech, attach_right)
	var/has_molten = FALSE
	for (var/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/thegun in themech.flat_equipment)
		if (istype(thegun, /obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/cryo))
			to_chat(user, span_warning("[themech] 已经安装了 [thegun]！"))
			return ITEM_INTERACT_BLOCKING
		if (istype(thegun, /obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/inferno))
			has_molten = TRUE
	if (has_molten)
		for (var/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/thegun in themech.flat_equipment)
			if (istype(thegun, /obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/inferno))
				thegun.equip_cooldown = 8
		equip_cooldown = 8
	return ..()

/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/inferno/try_attach_part(mob/user, obj/vehicle/sealed/mecha/themech, attach_right)
	var/has_cryo = FALSE
	for (var/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/thegun in themech.flat_equipment)
		if (istype(thegun, /obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/inferno))
			to_chat(user, span_warning("[themech] 已经安装了 [thegun]！"))
			return ITEM_INTERACT_BLOCKING
		if (istype(thegun, /obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/cryo))
			has_cryo = TRUE
	if (has_cryo)
		for (var/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/thegun in themech.flat_equipment)
			if (istype(thegun, /obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/cryo))
				thegun.equip_cooldown = 8
		equip_cooldown = 8
	return ..()

/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/detach(atom/moveto)
	for (var/obj/item/mecha_parts/mecha_equipment/weapon/energy/thermal/thermal_gun in chassis.flat_equipment)
		thermal_gun.equip_cooldown = 20
	. = ..()

//Exosuit-mounted kinetic accelerator
/obj/item/mecha_parts/mecha_equipment/weapon/energy/mecha_kineticgun
	name = "机甲原动能空气炮"
	desc = "一种安装在机甲上的采矿工具，在低压下会增加伤害。依靠内部供电充能，因此比手持版射击更远。"
	icon_state = "mecha_kineticgun"
	energy_drain = 0.3 KILO JOULES
	projectile = /obj/projectile/kinetic/mech
	equip_cooldown = 1.6 SECONDS
	fire_sound = 'sound/items/weapons/kinetic_accel.ogg'
	harmful = TRUE
	mech_flags = EXOSUIT_MODULE_COMBAT | EXOSUIT_MODULE_WORKING

/obj/item/mecha_parts/mecha_equipment/weapon/energy/taser
	name = "\improper PBT \"调解人\" 安装式泰瑟枪"
	desc = "一种用于非致命的机甲装备，能够发射非致命的电击装置造成麻痹效果。"
	icon_state = "mecha_taser"
	energy_drain = 2 KILO JOULES
	equip_cooldown = 8
	projectile = /obj/projectile/energy/electrode
	fire_sound = 'sound/items/weapons/taser.ogg'
	firing_effect_type = /obj/effect/temp_visual/dir_setting/firing_effect


/obj/item/mecha_parts/mecha_equipment/weapon/honker
	name = "\improper 轰克儿 爆破 5000"
	desc = "小丑机甲装备，它将欢乐和喜悦传递给每个人。HONK!"
	icon_state = "mecha_honker"
	energy_drain = 2 KILO JOULES
	equip_cooldown = 150
	projectiles_per_shot = 0
	range = MECHA_MELEE|MECHA_RANGED
	kickback = FALSE
	mech_flags = EXOSUIT_MODULE_HONK

/obj/item/mecha_parts/mecha_equipment/weapon/honker/action(mob/source, atom/target, list/modifiers)
	if(!action_checks(target))
		return
	playsound(chassis, 'sound/items/airhorn/airhorn.ogg', 100, TRUE)
	to_chat(source, "[icon2html(src, source)]<font color='red' size='5'>HONK</font>")
	for(var/mob/living/carbon/M in ohearers(6, chassis))
		if(HAS_TRAIT(M, TRAIT_DEAF))
			continue
		var/turf/turf_check = get_turf(M)
		if(isspaceturf(turf_check) && !turf_check.Adjacent(src)) //in space nobody can hear you honk.
			continue
		to_chat(M, "<font color='red' size='7'>HONK</font>")
		M.SetSleeping(0)
		M.adjust_stutter(40 SECONDS)
		M.sound_damage(deafen = 30 SECONDS)
		M.Paralyze(60)
		if(prob(30))
			M.Stun(200)
			M.Unconscious(80)
		else
			M.set_jitter_if_lower(1000 SECONDS)

	log_message("Honked from [src.name]. HONK!", LOG_MECHA)
	var/turf/T = get_turf(src)
	message_admins("[ADMIN_LOOKUPFLW(source)] used a Mecha Honker in [ADMIN_VERBOSEJMP(T)]")
	source.log_message("used a Mecha Honker at [AREACOORD(T)].", LOG_GAME)
	source.log_message("used a Mecha Honker at [AREACOORD(T)].", LOG_ATTACK)
	return ..()


//Base ballistic weapon type
/obj/item/mecha_parts/mecha_equipment/weapon/ballistic
	name = "通用弹道武器"
	fire_sound = 'sound/items/weapons/gun/smg/shot.ogg'
	var/projectiles
	var/projectiles_cache //ammo to be loaded in, if possible.
	var/projectiles_cache_max
	var/disabledreload //For weapons with no cache (like the rockets) which are reloaded by hand
	var/ammo_type

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/get_snowflake_data()
	return list(
		"snowflake_id" = MECHA_SNOWFLAKE_ID_WEAPON_BALLISTIC,
		"projectiles" = projectiles,
		"max_magazine" = initial(projectiles),
		"projectiles_cache" = projectiles_cache,
		"projectiles_cache_max" = projectiles_cache_max,
		"disabledreload" = disabledreload,
		"ammo_type" = ammo_type,
	)

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/action_checks(target)
	if(!..())
		return FALSE
	if(projectiles <= 0)
		return FALSE
	return TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/handle_ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
	if(action == "reload")
		rearm()
		return TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/rearm()
	if(projectiles < initial(projectiles))
		var/projectiles_to_add = initial(projectiles) - projectiles
		if(!projectiles_cache)
			return FALSE
		if(projectiles_to_add <= projectiles_cache)
			projectiles = projectiles + projectiles_to_add
			projectiles_cache = projectiles_cache - projectiles_to_add
		else
			projectiles = projectiles + projectiles_cache
			projectiles_cache = 0
		log_message("Rearmed [src].", LOG_MECHA)
		return TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/needs_rearm()
	return projectiles <= 0


/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/action(mob/source, atom/target, list/modifiers)
	. = ..()
	if(!.)
		return
	projectiles -= projectiles_per_shot

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/carbine
	name = "\improper FNX-99 \"地狱\" 卡宾枪"
	desc = "一种用于作战的机甲装备，能够发射燃烧弹。"
	icon_state = "mecha_carbine"
	equip_cooldown = 10
	projectile = /obj/projectile/bullet/incendiary/fnx99
	projectiles = 24
	projectiles_cache = 24
	projectiles_cache_max = 96
	harmful = TRUE
	ammo_type = MECHA_AMMO_INCENDIARY

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/silenced
	name = "\improper S.H.H. \"寂灭\" 卡宾枪"
	desc = "一种用于作战的机甲装备，一种被哑剧发明的武器，实战测试表明，目标在倒下之前根本无法发出叫声。"
	fire_sound = 'sound/items/weapons/gun/general/heavy_shot_suppressed.ogg'
	icon_state = "mecha_mime"
	equip_cooldown = 30
	projectile = /obj/projectile/bullet/mime
	projectiles = 6
	projectiles_cache = 999
	harmful = TRUE
	mech_flags = EXOSUIT_MODULE_RETICENCE

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/scattershot
	name = "\improper LBX AC 10 \"霰弹\""
	desc = "一种用于作战的机甲装备，可以打出一大片弹丸。"
	icon_state = "mecha_scatter"
	equip_cooldown = 20
	projectile = /obj/projectile/bullet/scattershot
	projectiles = 40
	projectiles_cache = 40
	projectiles_cache_max = 160
	projectiles_per_shot = 4
	variance = 25
	harmful = TRUE
	ammo_type = MECHA_AMMO_BUCKSHOT

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/lmg
	name = "\improper AC-2 轻机枪"
	desc = "一种用于作战的机甲装备，能够一次快速发射三发子弹。"
	icon_state = "mecha_uac2"
	equip_cooldown = 10
	projectile = /obj/projectile/bullet/lmg
	projectiles = 300
	projectiles_cache = 300
	projectiles_cache_max = 1200
	projectiles_per_shot = 3
	variance = 6
	randomspread = 1
	projectile_delay = 2
	harmful = TRUE
	ammo_type = MECHA_AMMO_LMG

/// Missiles
/// SRM-8 Missile Rack - Used by Nuclear Operatives - Explodes when it hits anything
/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/missile_rack
	name = "\improper SRM-8 导弹架"
	desc = "一种用于战斗外骨骼的武器。发射短程导弹。"
	icon_state = "mecha_missilerack"
	projectile = /obj/projectile/bullet/rocket/srm
	fire_sound = 'sound/items/weapons/gun/general/rocket_launch.ogg'
	projectiles = 8
	projectiles_cache = 0
	projectiles_cache_max = 0
	disabledreload = TRUE
	equip_cooldown = 60
	harmful = TRUE
	ammo_type = MECHA_AMMO_MISSILE_SRM

/// PEP-6 Missile Rack - Used by Robotics - Explodes only when it hits dense objects like walls, borgs and mechs
/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/missile_rack/breaching
	name = "\improper PEP-6 导弹发射架"
	desc = "一种用于战斗外骨骼的武器。发射精密爆破弹，设计为仅在击中结构化目标（包括墙壁、外骨骼和机械人）时引爆。"
	icon_state = "mecha_missilerack_six"
	projectile = /obj/projectile/bullet/rocket/pep
	fire_sound = 'sound/items/weapons/gun/general/rocket_launch.ogg'
	projectiles = 6
	projectiles_cache = 0
	projectiles_cache_max = 0
	disabledreload = TRUE
	equip_cooldown = 60
	harmful = TRUE
	ammo_type = MECHA_AMMO_MISSILE_PEP

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher
	var/missile_speed = 2
	var/missile_range = 30
	var/diags_first = FALSE

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/action(mob/source, atom/target, list/modifiers)
	if(!action_checks(target))
		return
	TIMER_COOLDOWN_START(chassis, COOLDOWN_MECHA_EQUIPMENT(type), equip_cooldown)
	chassis.use_energy(energy_drain)
	var/newtonian_target = dir2angle(REVERSE_DIR(chassis.dir))
	var/obj/O = new projectile(chassis.loc)
	playsound(chassis, fire_sound, 50, TRUE)
	log_message("Launched a [O.name] from [name], targeting [target].", LOG_MECHA)
	projectiles--
	proj_init(O, source)
	O.throw_at(target, missile_range, missile_speed, source, FALSE, diagonals_first = diags_first)
	sleep(max(0, projectile_delay))
	if(kickback)
		chassis.newtonian_move(newtonian_target)
	return TRUE

//used for projectile initilisation (priming flashbang) and additional logging
/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/proc/proj_init(obj/O, mob/user)
	return


/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/flashbang
	name = "\improper SGL-6 榴弹发射器"
	desc = "一种用于作战的机甲装备，可以发射闪光弹。"
	icon_state = "mecha_grenadelnchr"
	projectile = /obj/item/grenade/flashbang
	fire_sound = 'sound/items/weapons/gun/general/grenade_launch.ogg'
	projectiles = 6
	projectiles_cache = 6
	projectiles_cache_max = 24
	missile_speed = 1.5
	equip_cooldown = 60
	ammo_type = MECHA_AMMO_FLASHBANG
	var/det_time = 20

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/flashbang/proj_init(obj/item/grenade/flashbang/F, mob/user)
	var/turf/T = get_turf(src)
	message_admins("[ADMIN_LOOKUPFLW(user)] fired a [F] in [ADMIN_VERBOSEJMP(T)]")
	user.log_message("fired a [F] in [AREACOORD(T)].", LOG_GAME)
	user.log_message("fired a [F] in [AREACOORD(T)].", LOG_ATTACK)
	addtimer(CALLBACK(F, TYPE_PROC_REF(/obj/item/grenade/flashbang, detonate)), det_time)

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/flashbang/clusterbang //Because I am a heartless bastard -Sieve //Heartless? for making the poor man's honkblast? - Kaze
	name = "\improper SOB-3 榴弹发射器"
	desc = "一种用于作战的机甲装备，能够发射预先准备好的连环爆炸弹。你这个畜生。"
	projectiles = 3
	projectiles_cache = 0
	projectiles_cache_max = 0
	disabledreload = TRUE
	projectile = /obj/item/grenade/clusterbuster
	equip_cooldown = 90
	ammo_type = MECHA_AMMO_CLUSTERBANG

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/banana_mortar
	name = "香蕉迫击炮"
	desc = "小丑机甲的装备，可以发射香蕉皮"
	icon_state = "mecha_bananamrtr"
	projectile = /obj/item/grown/bananapeel
	fire_sound = 'sound/items/bikehorn.ogg'
	projectiles = 15
	missile_speed = 1.5
	projectiles_cache = 999
	projectiles_cache_max = 999
	equip_cooldown = 20
	mech_flags = EXOSUIT_MODULE_HONK
	ammo_type = MECHA_AMMO_BANANA_PEEL

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/mousetrap_mortar
	name = "老鼠夹迫击炮"
	desc = "小丑机甲的装备。可以发射武装捕鼠器。"
	icon_state = "mecha_mousetrapmrtr"
	projectile = /obj/item/assembly/mousetrap/armed
	fire_sound = 'sound/items/bikehorn.ogg'
	projectiles = 15
	missile_speed = 1.5
	projectiles_cache = 999
	projectiles_cache_max = 999
	equip_cooldown = 10
	mech_flags = EXOSUIT_MODULE_HONK
	ammo_type = MECHA_AMMO_MOUSETRAP

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/mousetrap_mortar/proj_init(obj/item/assembly/mousetrap/armed/M)
	M.secured = TRUE

//Classic extending punching glove, but weaponised!
/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/punching_glove
	name = "\improper 艺术就是打你脸"
	desc = "小丑外骨骼机甲，把乐趣糊你脸上！"
	icon_state = "mecha_punching_glove"
	energy_drain = 250
	equip_cooldown = 20
	range = MECHA_MELEE|MECHA_RANGED
	missile_range = 5
	projectile = /obj/item/punching_glove
	fire_sound = 'sound/items/bikehorn.ogg'
	projectiles = 10
	projectiles_cache = 999
	projectiles_cache_max = 999
	harmful = TRUE
	diags_first = TRUE
	/// Damage done by the glove on contact. Also used to determine throw distance (damage / 5)
	var/punch_damage = 35
	mech_flags = EXOSUIT_MODULE_HONK
	ammo_type = MECHA_AMMO_PUNCHING_GLOVE

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/punching_glove/get_snowflake_data()
	. = ..()
	.["mode"] = harmful ? "LETHAL FISTING" : "Cuddles"
	.["mode_label"] = "Honk Severity"

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/punching_glove/handle_ui_act(action, list/params)
	. = ..()
	if(action == "change_mode")
		harmful = !harmful
		if(harmful)
			to_chat(usr, "[icon2html(src, usr)][span_warning("Lethal Fisting Enabled.")]")
		else
			to_chat(usr, "[icon2html(src, usr)][span_warning("Lethal Fisting Disabled.")]")
		return TRUE

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/punching_glove/action(mob/source, atom/target, list/modifiers)
	. = ..()
	if(.)
		to_chat(usr, "[icon2html(src, usr)]<font color='red' size='5'>HONK</font>")

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/punching_glove/proj_init(obj/item/punching_glove/PG)
	if(!istype(PG))
		return

	if(harmful)
		PG.throwforce = punch_damage
	else
		PG.throwforce = 0

	chassis.Beam(PG, icon_state = "chain", time = missile_range * 20, maxdistance = missile_range + 2)

/obj/item/punching_glove
	name = "拳击手套"
	desc = "HONK来袭"
	throwforce = 35
	icon = 'icons/obj/toys/toy.dmi'
	icon_state = "punching_glove"

/obj/item/punching_glove/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
	if(!..())
		if(ismovable(hit_atom))
			var/atom/movable/AM = hit_atom
			AM.safe_throw_at(get_edge_target_turf(AM,get_dir(src, AM)), clamp(round(throwforce/5), 2, 20), 2, force = MOVE_FORCE_EXTREMELY_STRONG) //Throws them equal to damage/5, with a min range of 2 and max range of 20
		qdel(src)

///dark honk weapons

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/banana_mortar/bombanana
	name = "香蕉炸弹迫击炮"
	desc = "用于小丑机甲的装备。能发射爆炸的香蕉皮。"
	icon_state = "mecha_bananamrtr"
	projectile = /obj/item/grown/bananapeel/bombanana
	projectiles = 8
	projectiles_cache = 999
	mech_flags = EXOSUIT_MODULE_HONK

/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/launcher/flashbang/tearstache
	name = "\improper HONKeR-6榴弹发射器"
	desc = "一种用于作战的机甲装备，可以发射催泪弹。"
	icon_state = "mecha_grenadelnchr"
	projectile = /obj/item/grenade/chem_grenade/teargas/moustache
	fire_sound = 'sound/items/weapons/gun/general/grenade_launch.ogg'
	projectiles = 6
	missile_speed = 1.5
	projectiles_cache = 999
	equip_cooldown = 60
	det_time = 20
	mech_flags = EXOSUIT_MODULE_HONK

///long claw of the law
/obj/item/mecha_parts/mecha_equipment/weapon/paddy_claw
	name = "液压爪"
	desc = "一种经过改装的液压夹钳，专为帕迪外骨骼设计。用于非致命性拘捕嫌疑人。"
	icon_state = "paddy_claw"
	equip_cooldown = 15
	energy_drain = 10
	tool_behaviour = TOOL_RETRACTOR
	range = MECHA_MELEE
	toolspeed = 0.8
	mech_flags = EXOSUIT_MODULE_PADDY
	projectiles_per_shot = 0
	///Chassis but typed for the cargo_hold var
	var/obj/vehicle/sealed/mecha/ripley/secmech
	///Audio for using the hydraulic clamp
	var/clampsound = 'sound/vehicles/mecha/hydraulic.ogg'
	///Var for the cuff type. Basically stole how cuffing works from secbots
	var/cuff_type = /obj/item/restraints/handcuffs/cable/zipties/used
	///Var for autocuff, can be toggled in the mech interface.
	var/autocuff = TRUE


/obj/item/mecha_parts/mecha_equipment/weapon/paddy_claw/attach(obj/vehicle/sealed/mecha/new_mecha)
	. = ..()
	secmech = chassis

/obj/item/mecha_parts/mecha_equipment/weapon/paddy_claw/detach(atom/moveto)
	secmech = null
	return ..()

/obj/item/mecha_parts/mecha_equipment/weapon/paddy_claw/action(mob/source, atom/target, list/modifiers)
	if(!secmech.cargo_hold) //We did try
		CRASH("Mech [chassis] has a claw device, but no internal storage. This should be impossible.")
	if(!action_checks(target))
		return
	if(isliving(target))
		. = ..()
		var/mob/living/mobtarget = target
		if(mobtarget.move_resist == MOVE_FORCE_OVERPOWERING) //No megafauna or bolted AIs, please.
			balloon_alert(source, "太强了！")
			return
		if(secmech.cargo_hold.contents.len >= secmech.cargo_hold.cargo_capacity)
			balloon_alert(source, "没空间了！")
			return

		playsound(chassis, clampsound, 50, FALSE, -6)
		mobtarget.visible_message(span_notice("[chassis]将[mobtarget]抬入其内部拘留舱。"),span_userdanger("[chassis]用[src]抓住你，准备将你装入[secmech.cargo_hold]！"))
		if(!do_after_cooldown(mobtarget, source, flags = MECH_DO_AFTER_DIR_CHANGE_FLAG|MECH_DO_AFTER_ADJACENCY_FLAG))
			return
		mobtarget.forceMove(secmech.cargo_hold)
		log_message("Loaded [mobtarget]. Cargo compartment capacity: [secmech.cargo_hold.cargo_capacity - secmech.cargo_hold.contents.len]", LOG_MECHA)
		to_chat(source, "[icon2html(src, source)][span_notice("[mobtarget] successfully loaded.")]")
		to_chat(mobtarget, "[span_warning("You have been moved into [secmech.cargo_hold]. You can attempt to resist out if you wish.")]")
		if(autocuff && iscarbon(target))
			var/mob/living/carbon/carbontarget = target
			carbontarget.set_handcuffed(new cuff_type(carbontarget))
		return

	if(istype(target, /obj/machinery/door))
		. = ..()
		var/obj/machinery/door/target_door = target
		playsound(chassis, clampsound, 50, FALSE, -6)
		target_door.try_to_crowbar(src, source)
		return

/obj/item/mecha_parts/mecha_equipment/weapon/paddy_claw/get_snowflake_data()
	return list(
		"snowflake_id" = MECHA_SNOWFLAKE_ID_CLAW,
		"autocuff" = autocuff,
	)

/obj/item/mecha_parts/mecha_equipment/weapon/paddy_claw/handle_ui_act(action, list/params)
	switch(action)
		if("togglecuff")
			autocuff = !autocuff
			return TRUE
