import { Food } from '../PreferencesMenu/types';

export const TYPE_ICONS = {
  'Can Make': 'utensils',
  [Food.Alcohol]: 'wine-glass',
  [Food.Bloody]: 'tint', // NOVA EDIT ADDITION - Hemophage Food
  [Food.Breakfast]: 'sun',
  [Food.Bugs]: 'bug',
  [Food.Cloth]: 'tshirt',
  [Food.Dairy]: 'cheese',
  [Food.Egg]: 'egg',
  [Food.Fried]: 'fire',
  [Food.Fruit]: 'apple-alt',
  [Food.Gore]: 'skull',
  [Food.Grain]: 'wheat-awn',
  [Food.Gross]: 'trash',
  [Food.Junkfood]: 'pizza-slice',
  [Food.Meat]: 'bacon',
  [Food.Nuts]: 'seedling',
  [Food.Oranges]: 'apple-alt',
  [Food.Pineapple]: 'apple-alt',
  [Food.Raw]: 'drumstick-bite',
  [Food.Seafood]: 'fish',
  [Food.Stone]: 'gem',
  [Food.Sugar]: 'candy-cane',
  [Food.Toxic]: 'biohazard',
  [Food.Vegetables]: 'carrot',
} as const;

export const CATEGORY_ICONS_CRAFTING = {
  'Can Make': 'hammer',
  'Weapons Melee': 'hand-fist',
  'Weapons Ranged': 'gun',
  'Weapon Ammo': 'box',
  Robotics: 'robot',
  Misc: 'shapes',
  Tribal: 'campground',
  Clothing: 'shirt',
  Drinks: 'wine-bottle',
  Chemistry: 'microscope',
  Atmospherics: 'fan',
  Structures: 'cube',
  Tiles: 'border-all',
  Windows: 'person-through-window',
  Doors: 'door-open',
  Furniture: 'chair',
  Equipment: 'calculator',
  Containers: 'briefcase',
  Tools: 'screwdriver-wrench',
  Entertainment: 'masks-theater',
  'Blood Cult': 'users',
  Construction: 'trowel-bricks',
} as const;

export const CATEGORY_ICONS_COOKING = {
  'Can Make': 'utensils',
  Appetizer: 'bread-slice',
  Bread: 'bread-slice',
  Burger: 'burger',
  Burrito: 'circle-o',
  Cake: 'cake-candles',
  Candy: 'candy-cane',
  Component: 'cubes',
  Cookie: 'cookie',
  Dessert: 'face-grin-beam-sweat',
  Frozen: 'ice-cream',
  Hemophage: 'tint', // NOVA EDIT ADDITION - Hemophage Food
  Italian: 'pizza-slice',
  Japanese: 'earth-asia',
  Lizard: 'dragon',
  Martian: 'globe',
  Meat: 'bacon',
  Mexican: 'earth-americas',
  Mothic: 'shirt',
  Noodles: 'wheat-awn',
  Pastry: 'cookie',
  Pie: 'chart-pie',
  Pizza: 'pizza-slice',
  Rice: 'bowl-rice',
  Salad: 'leaf',
  Sandwich: 'hotdog',
  Soup: 'mug-hot',
  Sushi: 'fish',
  Taco: 'circle-o',
  Terran: 'earth-europe',
  Teshari: 'feather-pointed', // NOVA EDIT ADDITION - Teshari Food
  Uncategorized: 'shapes',
  'Main Course': 'drumstick-bite',
  Breakfast: 'sun',
  Snack: 'compress',
  Condiment: 'bottle-water',
} as const;

// NOVA EDIT ADDITION START - i18n: display labels for tool_behaviors. The raw value
// (e.g. "knife") is an icon-class key AND a comparison id, so it must stay English;
// only the shown text is localized. Keep in sync with #define TOOL_* in code/__DEFINES/tools.dm.
export const TOOL_LABELS: Record<string, string> = {
  crowbar: '撬棍',
  multitool: '多用工具',
  screwdriver: '螺丝刀',
  cutters: '剪线钳',
  wrench: '扳手',
  welder: '焊枪',
  analyzer: '分析仪',
  mining: '采矿工具',
  shovel: '铲子',
  retractor: '牵开器',
  hemostat: '止血钳',
  cautery: '烧灼器',
  drill: '手钻',
  scalpel: '手术刀',
  saw: '锯',
  bonesetter: '接骨器',
  knife: '刀',
  bloodfilter: '血液过滤器',
  'rolling pin': '擀面杖',
  rustscraper: '除锈器',
  billow: '风箱',
  tong: '夹钳',
};
// NOVA EDIT ADDITION END
